-- MySQL Script generated by MySQL Workbench
-- Fri Mar  8 19:19:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oj
-- -----------------------------------------------------
-- oj for c++
DROP SCHEMA IF EXISTS `oj` ;

-- -----------------------------------------------------
-- Schema oj
--
-- oj for c++
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oj` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `oj` ;

-- -----------------------------------------------------
-- Table `oj`.`stat_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oj`.`stat_class` ;

CREATE TABLE IF NOT EXISTS `oj`.`stat_class` (
  `idstat_class` INT NOT NULL,
  `stat_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstat_class`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oj`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oj`.`teacher` ;

CREATE TABLE IF NOT EXISTS `oj`.`teacher` (
  `idteacher` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `qq` VARCHAR(45) NULL,
  `phone` CHAR(11) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idteacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oj`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oj`.`class` ;

CREATE TABLE IF NOT EXISTS `oj`.`class` (
  `idclass` INT NOT NULL AUTO_INCREMENT,
  `classname` VARCHAR(45) NOT NULL,
  `idteacher` VARCHAR(45) NULL,
  `semester` VARCHAR(45) NULL,
  `stu_amount` VARCHAR(45) NULL,
  `opendate` DATETIME NULL,
  `closedate` DATETIME NULL,
  `idstatus` INT NULL,
  PRIMARY KEY (`idclass`),
  UNIQUE INDEX `classname_UNIQUE` (`classname` ASC) VISIBLE,
  INDEX `idstatus_idx` (`idstatus` ASC) VISIBLE,
  INDEX `idteacher_idx` (`idteacher` ASC) VISIBLE,
  CONSTRAINT `idstatus`
    FOREIGN KEY (`idstatus`)
    REFERENCES `oj`.`stat_class` (`idstat_class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idteacher`
    FOREIGN KEY (`idteacher`)
    REFERENCES `oj`.`teacher` (`idteacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oj`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oj`.`student` ;

CREATE TABLE IF NOT EXISTS `oj`.`student` (
  `idstudent` VARCHAR(45) NOT NULL,
  `name` VARCHAR(15) NULL,
  `idclass` INT NULL DEFAULT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nature_class` VARCHAR(45) NULL,
  PRIMARY KEY (`idstudent`),
  INDEX `idclass_idx` (`idclass` ASC) VISIBLE,
  CONSTRAINT `idclass`
    FOREIGN KEY (`idclass`)
    REFERENCES `oj`.`class` (`idclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oj`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oj`.`admin` ;

CREATE TABLE IF NOT EXISTS `oj`.`admin` (
  `idadmin` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oj`.`stat_contest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oj`.`stat_contest` ;

CREATE TABLE IF NOT EXISTS `oj`.`stat_contest` (
  `idstat_contest` INT NOT NULL,
  `stat_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstat_contest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oj`.`assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oj`.`assignment` ;

CREATE TABLE IF NOT EXISTS `oj`.`assignment` (
  `idassignment` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `problem_list` VARCHAR(45) NOT NULL,
  `commence` DATETIME NOT NULL,
  `deadline` DATETIME NOT NULL,
  `to_class` VARCHAR(45) NOT NULL,
  `idstatus` INT NULL,
  PRIMARY KEY (`idassignment`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  INDEX `idassignstatus_idx` (`idstatus` ASC) VISIBLE,
  CONSTRAINT `idassignstatus`
    FOREIGN KEY (`idstatus`)
    REFERENCES `oj`.`stat_contest` (`idstat_contest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oj`.`contest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oj`.`contest` ;

CREATE TABLE IF NOT EXISTS `oj`.`contest` (
  `idcontest` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `problem_list` VARCHAR(45) NOT NULL,
  `commence` DATETIME NOT NULL,
  `deadline` DATETIME NOT NULL,
  `to_class` VARCHAR(45) NOT NULL,
  `idstatus` INT NULL,
  PRIMARY KEY (`idcontest`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  INDEX `idstatus_idx` (`idstatus` ASC) VISIBLE,
  CONSTRAINT `idconteststatus`
    FOREIGN KEY (`idstatus`)
    REFERENCES `oj`.`stat_contest` (`idstat_contest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oj`.`problem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oj`.`problem` ;

CREATE TABLE IF NOT EXISTS `oj`.`problem` (
  `idproblem` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `input` VARCHAR(90) NOT NULL,
  `output` VARCHAR(90) NOT NULL,
  `committed` INT NULL,
  `passed` INT NULL,
  `tag` VARCHAR(45) NULL,
  PRIMARY KEY (`idproblem`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oj`.`stat_judge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oj`.`stat_judge` ;

CREATE TABLE IF NOT EXISTS `oj`.`stat_judge` (
  `idstat_judge` INT NOT NULL,
  `stat_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstat_judge`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oj`.`submit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oj`.`submit` ;

CREATE TABLE IF NOT EXISTS `oj`.`submit` (
  `idsubmit` INT NOT NULL AUTO_INCREMENT,
  `idstudent` VARCHAR(45) NOT NULL,
  `idproblem` INT NOT NULL,
  `time` TIMESTAMP NOT NULL,
  `sourcecode` VARCHAR(45) NOT NULL,
  `console_output` VARCHAR(45) NULL,
  `idstatus` INT NULL,
  `duration` INT NULL,
  `space` INT NULL,
  `score` VARCHAR(45) NULL,
  PRIMARY KEY (`idsubmit`),
  INDEX `idproblem_idx` (`idproblem` ASC) VISIBLE,
  INDEX `idstatus_idx` (`idstatus` ASC) VISIBLE,
  INDEX `idstudent_idx` (`idstudent` ASC) VISIBLE,
  CONSTRAINT `idproblem`
    FOREIGN KEY (`idproblem`)
    REFERENCES `oj`.`problem` (`idproblem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idsubmitstatus`
    FOREIGN KEY (`idstatus`)
    REFERENCES `oj`.`stat_judge` (`idstat_judge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idstudent`
    FOREIGN KEY (`idstudent`)
    REFERENCES `oj`.`student` (`idstudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `oj`.`stat_class`
-- -----------------------------------------------------
START TRANSACTION;
USE `oj`;
INSERT INTO `oj`.`stat_class` (`idstat_class`, `stat_name`) VALUES (1, '等待确认');
INSERT INTO `oj`.`stat_class` (`idstat_class`, `stat_name`) VALUES (2, '开启');
INSERT INTO `oj`.`stat_class` (`idstat_class`, `stat_name`) VALUES (3, '关闭');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oj`.`teacher`
-- -----------------------------------------------------
START TRANSACTION;
USE `oj`;
INSERT INTO `oj`.`teacher` (`idteacher`, `name`, `qq`, `phone`, `email`, `password`) VALUES ('1', '李绘卓', '9090950', '12377778888', 'lihuihzuo@qq.com', '123456');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oj`.`class`
-- -----------------------------------------------------
START TRANSACTION;
USE `oj`;
INSERT INTO `oj`.`class` (`idclass`, `classname`, `idteacher`, `semester`, `stu_amount`, `opendate`, `closedate`, `idstatus`) VALUES (1, '18秋软件测试', '1', '20182', '54', NULL, NULL, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `oj`.`student`
-- -----------------------------------------------------
START TRANSACTION;
USE `oj`;
INSERT INTO `oj`.`student` (`idstudent`, `name`, `idclass`, `password`, `nature_class`) VALUES ('1', '王先金', 1, '123456', '软件1504');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oj`.`admin`
-- -----------------------------------------------------
START TRANSACTION;
USE `oj`;
INSERT INTO `oj`.`admin` (`idadmin`, `password`) VALUES ('555555', '123456');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oj`.`stat_contest`
-- -----------------------------------------------------
START TRANSACTION;
USE `oj`;
INSERT INTO `oj`.`stat_contest` (`idstat_contest`, `stat_name`) VALUES (1, '未开始');
INSERT INTO `oj`.`stat_contest` (`idstat_contest`, `stat_name`) VALUES (2, '草稿');
INSERT INTO `oj`.`stat_contest` (`idstat_contest`, `stat_name`) VALUES (3, '进行中');
INSERT INTO `oj`.`stat_contest` (`idstat_contest`, `stat_name`) VALUES (4, '已结束');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oj`.`problem`
-- -----------------------------------------------------
START TRANSACTION;
USE `oj`;
INSERT INTO `oj`.`problem` (`idproblem`, `title`, `description`, `input`, `output`, `committed`, `passed`, `tag`) VALUES (1, 'A+B', '给出两个整数 aa 和 bb , 求他们的和。', '1 2', '3', NULL, NULL, '简单,水题');

COMMIT;


-- -----------------------------------------------------
-- Data for table `oj`.`stat_judge`
-- -----------------------------------------------------
START TRANSACTION;
USE `oj`;
INSERT INTO `oj`.`stat_judge` (`idstat_judge`, `stat_name`) VALUES (1, 'Accept');
INSERT INTO `oj`.`stat_judge` (`idstat_judge`, `stat_name`) VALUES (2, 'Compile Error');
INSERT INTO `oj`.`stat_judge` (`idstat_judge`, `stat_name`) VALUES (3, 'Runtime Error');
INSERT INTO `oj`.`stat_judge` (`idstat_judge`, `stat_name`) VALUES (4, 'Wrong Answer');
INSERT INTO `oj`.`stat_judge` (`idstat_judge`, `stat_name`) VALUES (5, 'Presentation Error');

COMMIT;

